### ISSUE TITLE
Improve console..

### ISSUE THREAD

**Issue by ayan312002** [DaGamingBoss/SpartanOS#5]
The console needs to be improve. More user interface should be added..

**Comment by DaGamingBoss** [comment]
I am aware of this. I'm still to improve my keyboard stuff and add some useful programs, but I'm implementing Userspace now. After that, i will implement some more functions to the console, to make it more bash-like.

Thanks for the feedback!

**Comment by ayan312002** [comment]
It would be nice if you add some docs related to compiling..

**Comment by DaGamingBoss** [comment]
You just gave me something to do ;)

**Comment by ayan312002** [comment]
Lol you are so active.. never thought that..

**Comment by ayan312002** [comment]
I have a cross compiler not a target specific so i can't compile your kernel now..

**Comment by DaGamingBoss** [comment]
Yeah, i made a patch of gcc-5.3.0 and binutils-2.24. The patches are in the root project directory. I'm going to make some docs for compilation. Never even thought anybody would have trouble compiling ( Thats what you get for not thinking correctly).

**Comment by ayan312002** [comment]
Thats ok.. atleast i can give you updates

**Comment by DaGamingBoss** [comment]
Already created the needed documentation, if you need any help just say !
